{% set name = "netaddr" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b46fa9b1a2d71fd5de9e4a3784ef339700a53a08c8040f08baf5f1194da0128

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - netaddr
    - netaddr.eui
    - netaddr.ip
    - netaddr.strategy

about:
  home: http://github.com/drkjam/netaddr
  license_file: LICENSE
  license: BSD 3-clause
  license_family: BSD
  summary: 'Pythonic manipulation of IPv4, IPv6, CIDR, EUI and MAC network addresses'
  dev_url: https://github.com/drkjam/netaddr
  doc_url: https://netaddr.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - mariusvniekerk
    - drkjam
