{% set version = "1.3.0" %}

package:
  name: netaddr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netaddr/netaddr-{{ version }}.tar.gz
  sha256: 5c3c3d9895b551b763779ba7db7a03487dc1f8e3b385af819af341ae9ef6e48a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - netaddr = "netaddr.cli:main"

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7

test:
  imports:
    - netaddr
    - netaddr.eui
    - netaddr.ip
    - netaddr.strategy

about:
  home: http://github.com/netaddr/netaddr
  license_file: LICENSE.rst
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Pythonic manipulation of IPv4, IPv6, CIDR, EUI and MAC network addresses'
  dev_url: https://github.com/netaddr/netaddr
  doc_url: https://netaddr.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - tschoonj
    - anguslees
    - mariusvniekerk
    - drkjam
