{% set version = "0.7.19" %}

package:
  name: netaddr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netaddr/netaddr-{{ version }}.tar.gz
  sha256: 38aeec7cdd035081d3a4c306394b19d677623bf76fa0913f6695127c7753aefd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - netaddr
    - netaddr.eui
    - netaddr.ip
    - netaddr.strategy

about:
  home: http://github.com/drkjam/netaddr
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Pythonic manipulation of IPv4, IPv6, CIDR, EUI and MAC network addresses'
  dev_url: https://github.com/drkjam/netaddr
  doc_url: https://netaddr.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - tschoonj
    - anguslees
    - mariusvniekerk
    - drkjam
